version: "3.4"

services:
  nodes-server:
    container_name: node-server
    build:
      context: ./
      target: debug
    volumes:
      - ./:/usr/src/NodeES6
    hostname: nodejs
    restart: always
    ports:
      - 5000:5000
      - 9229:9229

  mongo:
    container_name: mongoDB
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_DATABASE=pastime
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root_password
    volumes:
      - C:/Users/leduc/Desktop/mongodata:/data/db
